version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_prueba
    environment:
      POSTGRES_DB: prueba_tecnica
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_prueba
    ports:
      - "6379:6379"

volumes:
  postgres_data:
